import { app, BrowserWindow, net, protocol, shell } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
import { pathToFileURL } from 'url';
import { GAME_BUNDLE_ORIGIN } from './bridge';

/**
 * Dev-mode game bundle: serves the Joymixa web app from local assets over a
 * privileged `app://` scheme and proxies its backend traffic in the main process.
 *
 * Why a custom protocol instead of `loadFile` + hash routing (the route the research
 * doc sketched): `app://` gives the page a real, secure origin, so
 *  - Angular's default PathLocationStrategy keeps working (catch-all -> index.html),
 *    meaning zero changes to the web app;
 *  - `/api/*` and `/media/*` are same-origin for the renderer — the handler forwards
 *    them to the backend with `net.fetch`, so there is no CORS surface at all and
 *    request bodies survive (the Android WebView proxy cannot forward POST bodies);
 *  - `ws://127.0.0.1:20809` to the bridge is allowed from the secure origin because
 *    loopback is exempt from mixed-content blocking (same as the shipping HTTPS page).
 *
 * The game assets live in `game/` (generated by scripts/copy-game-assets.sh, gitignored,
 * never committed — public repo).
 */

/** Origin the game is served from — single source of truth in bridge.ts, where the
 *  WebSocket origin allowlist admits it. Scheme derived, never restated. */
const GAME_ORIGIN = GAME_BUNDLE_ORIGIN;
const GAME_SCHEME = new URL(GAME_ORIGIN).protocol.replace(/:$/, '');

/** Backend the /api and /media proxies target. Staging matches `yarn build-staging-fast`
 *  game builds and the Android debug bundle. */
const BACKEND_URL = process.env.JOYMIXA_BACKEND ?? 'https://test.joymixa.com';

/** Paths forwarded to the backend instead of the local asset dir. */
const PROXY_PREFIXES = ['/api/', '/media/'];

let gameWindow: BrowserWindow | null = null;

/** Where the copied game assets live: repo root in dev, resources/ when packaged. */
export function gameAssetsDir(): string {
  return app.isPackaged
    ? path.join(process.resourcesPath, 'game')
    : path.join(app.getAppPath(), 'game');
}

/** True when a game build has been copied in (gates the tray item / bundle mode). */
export function hasGameAssets(): boolean {
  return fs.existsSync(path.join(gameAssetsDir(), 'index.html'));
}

/**
 * Must run before app 'ready'. Registers the privileged scheme and the Chromium
 * switches bundle mode needs:
 * - standard/secure: real origin, secure context (Web Audio, localStorage, loopback WS);
 * - supportFetchAPI/stream: the app fetches soundbank media from this scheme;
 * - autoplay switch: Android-bundle parity (`mediaPlaybackRequiresUserGesture=false`) —
 *   the game still has its own unmute gesture, this only removes the Chromium layer;
 * - JOYMIXA_CDP_PORT: opt-in remote-debugging endpoint so the running bundle can be
 *   driven/verified over CDP without touching the dev browser on :9222.
 */
export function initGameBundle(): void {
  protocol.registerSchemesAsPrivileged([
    { scheme: GAME_SCHEME, privileges: { standard: true, secure: true, supportFetchAPI: true, stream: true } },
  ]);
  app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required');
  const cdpPort = process.env.JOYMIXA_CDP_PORT;
  if (cdpPort && /^\d+$/.test(cdpPort)) {
    app.commandLine.appendSwitch('remote-debugging-port', cdpPort);
  }
}

/** Strip headers that describe the renderer's app:// context, not the proxied request. */
function proxyHeaders(request: Request): Headers {
  const headers = new Headers(request.headers);
  headers.delete('origin');
  headers.delete('referer');
  // Let net.fetch negotiate encoding itself; forwarding the renderer's value risks
  // serving content-encoded bytes it then does not decode.
  headers.delete('accept-encoding');
  return headers;
}

function proxyToBackend(request: Request, url: URL): Promise<Response> {
  const target = `${BACKEND_URL}${url.pathname}${url.search}`;
  const init: RequestInit & { duplex?: string } = {
    method: request.method,
    headers: proxyHeaders(request),
    redirect: 'follow',
  };
  if (request.method !== 'GET' && request.method !== 'HEAD') {
    init.body = request.body;
    // Required by fetch when the body is a stream.
    init.duplex = 'half';
  }
  return net.fetch(target, init);
}

/**
 * Serve a local game asset. Non-existent extension-less paths fall through to
 * index.html (the Angular router owns them); missing real files (e.g. a stale chunk
 * name) must 404 rather than answer with HTML.
 */
function serveGameAsset(url: URL): Promise<Response> {
  const root = gameAssetsDir();
  const requested = decodeURIComponent(url.pathname);
  const resolved = path.normalize(path.join(root, requested));

  // Path-traversal guard: everything served must stay inside the asset dir.
  if (resolved !== root && !resolved.startsWith(root + path.sep)) {
    return Promise.resolve(new Response('Forbidden', { status: 403 }));
  }

  const isFile = fs.existsSync(resolved) && fs.statSync(resolved).isFile();
  if (isFile) {
    return net.fetch(pathToFileURL(resolved).toString());
  }
  if (path.extname(resolved) === '') {
    return net.fetch(pathToFileURL(path.join(root, 'index.html')).toString());
  }
  return Promise.resolve(new Response('Not found', { status: 404 }));
}

/** Must run on/after app 'ready'. */
export function setupGameProtocol(): void {
  protocol.handle(GAME_SCHEME, async (request) => {
    const url = new URL(request.url);
    try {
      if (PROXY_PREFIXES.some((p) => url.pathname.startsWith(p))) {
        return await proxyToBackend(request, url);
      }
      return await serveGameAsset(url);
    } catch (err) {
      console.error(`[bundle] ${request.method} ${url.pathname} failed:`, err);
      return new Response('Bundle proxy error', { status: 502 });
    }
  });
}

export function createGameWindow(preloadEntry: string): void {
  if (gameWindow && !gameWindow.isDestroyed()) {
    gameWindow.show();
    gameWindow.focus();
    return;
  }

  gameWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    // Matches the game's dark background so the window does not flash white while
    // the first paint is pending.
    backgroundColor: '#000000',
    autoHideMenuBar: true,
    webPreferences: {
      preload: preloadEntry,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // Same hardening stance as the status window: this window only ever shows the
  // bundled game. External links go to the OS browser; everything else is denied.
  gameWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (url.startsWith('https://')) void shell.openExternal(url);
    return { action: 'deny' };
  });
  gameWindow.webContents.on('will-navigate', (event, url) => {
    if (!url.startsWith(`${GAME_ORIGIN}/`)) {
      event.preventDefault();
      console.warn(`[bundle] blocked navigation attempt to: ${url}`);
    }
  });

  void gameWindow.loadURL(`${GAME_ORIGIN}/`);

  gameWindow.on('closed', () => {
    gameWindow = null;
  });
}
